### PR TITLE
Make compatible with maintained json-simple.

### PR DESCRIPTION
**Pull request by brettle**

### CODE REVIEW

**Review by CoolSpy3 — CHANGES_REQUESTED** [review]
Running this code produces "`Error with incoming message: [json.exception.type_error.302] type must be number, but is string`" as the values returned from json-simple are `Integer`s and `Double`s (determined programmatically at runtime using `getClass().getName()`) causing this code to determine that they are `String`s.

Edit: Just noticed [WPIWebSockets#8](https://github.com/DeepBlueRobotics/WPIWebSockets/pull/8). I will rereview.

**Comment by brettle** [comment]
> Running this code produces "`Error with incoming message: [json.exception.type_error.302] type must be number, but is string`" as the values returned from json-simple are `Integer`s and `Double`s (determined programmatically at runtime using `getClass().getName()`) causing this code to determine that they are `String`s.
> 
> Edit: Just noticed [WPIWebSockets#8](https://github.com/DeepBlueRobotics/WPIWebSockets/pull/8). I will rereview.

Sorry. Should have mentioned that in this PR.

**Review by CoolSpy3 — CHANGES_REQUESTED** [review]
This should be updated to apply the `BigInteger` and `BigDouble` changes to [template.java](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java). See [PropertyFilter.js](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/filters/PropertyFilter.js).

**Comment by brettle** [comment]
> This should be updated to apply the `BigInteger` and `BigDouble` changes to [template.java](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java). See [PropertyFilter.js](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/filters/PropertyFilter.js).

Other than what I just committed, I don't think any other changes are needed. For example, I've managed to get EncoderSims working properly without needing any other changes to the template.

**Comment by CoolSpy3** [comment]
> > This should be updated to apply the `BigInteger` and `BigDouble` changes to [template.java](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java). See [PropertyFilter.js](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/filters/PropertyFilter.js).
> 
> Other than what I just committed, I don't think any other changes are needed. For example, I've managed to get EncoderSims working properly without needing any other changes to the template.

[The lines you changed in SimDeviceSim](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/6c715226f6823f9ef63ea70b46548c0495662bc7/template/SimDeviceSim.java#L231-L236) are equivalent to [lines 271-273 in template](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java#L271-L273). They should be made consistent or else the sims will not be able to read values from WPILib (which I'm guessing is the cause behind [this commit](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/pull/3/commits/0a04bd018c8348da5e1285554fe299f8b06337d9)).

**Comment by CoolSpy3** [comment]
> > > This should be updated to apply the `BigInteger` and `BigDouble` changes to [template.java](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java). See [PropertyFilter.js](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/filters/PropertyFilter.js).
> > 
> > 
> > Other than what I just committed, I don't think any other changes are needed. For example, I've managed to get EncoderSims working properly without needing any other changes to the template.
> 
> [The lines you changed in SimDeviceSim](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/6c715226f6823f9ef63ea70b46548c0495662bc7/template/SimDeviceSim.java#L231-L236) are equivalent to [lines 271-273 in template](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java#L271-L273). They should be made consistent or else the sims will not be able to read values from WPILib (which I'm guessing is the cause behind [this commit](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/pull/3/commits/0a04bd018c8348da5e1285554fe299f8b06337d9)).

Fixed in: [WPIWebSockets commit: a483ed6019774f5f97055e0df36ebc236e826a9d](https://github.com/DeepBlueRobotics/WPIWebSockets/pull/8/commits/a483ed6019774f5f97055e0df36ebc236e826a9d)

**Comment by brettle** [comment]
> > > > This should be updated to apply the `BigInteger` and `BigDouble` changes to [template.java](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java). See [PropertyFilter.js](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/filters/PropertyFilter.js).
> > > 
> > > 
> > > Other than what I just committed, I don't think any other changes are needed. For example, I've managed to get EncoderSims working properly without needing any other changes to the template.
> > 
> > 
> > [The lines you changed in SimDeviceSim](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/6c715226f6823f9ef63ea70b46548c0495662bc7/template/SimDeviceSim.java#L231-L236) are equivalent to [lines 271-273 in template](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/blob/master/partials/template.java#L271-L273). They should be made consistent or else the sims will not be able to read values from WPILib (which I'm guessing is the cause behind [this commit](https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate/pull/3/commits/0a04bd018c8348da5e1285554fe299f8b06337d9)).
> 
> Fixed in: [WPIWebSockets commit: a483ed6019774f5f97055e0df36ebc236e826a9d](https://github.com/DeepBlueRobotics/WPIWebSockets/pull/8/commits/a483ed6019774f5f97055e0df36ebc236e826a9d)

So all good right?

**Review by CoolSpy3 — APPROVED** [review]

**Pull request merged**
